In [20]:
#this code is to calculate inner arithmetic and geometric similarity for tree-shaped netorks
from statistics import mean
import numpy as np
import pandas as pd
TreeShapedDataset=pd.read_excel('../input/tree-shaped-networks/Tree-Shaped Networks/ThreeOrderMorphologicalData.xlsx')
# Part 1 (Branch number arithmetic and geometric similarirty)
#Calculate arithmetic and geometric branch number bifurcation ratio
#initial values
Tem_Sn=np.zeros((1,2))
BRn_Arithmetic=np.zeros((9,1))
BRn_Geometric=np.zeros((9,1))
Sn_Arithmetic=np.zeros((9,1))
Sn_Geometric=np.zeros((9,1))
for j in range(9):
    for i in range(2):
        R1=TreeShapedDataset.iloc[i,j]
        R2=TreeShapedDataset.iloc[i+1,j]
        Tem_Sn[0,i]=R2/R1
#arithmetic branch numer bifurcation ratio
    BRn_Arithmetic[j,0]=np.average(Tem_Sn)  
#geometric branch numer bifurcation ratio
    BRn_Geometric[j,0]=np.exp(np.mean(np.log(Tem_Sn)))  
for z in range (9):
#BRn_Geometric[4,0] is the reference tree-shaped network
#Calculate arithmetic branch number similarity
    Thresholdn=np.abs((BRn_Arithmetic[4,0]-BRn_Arithmetic[z,0])/BRn_Arithmetic[4,0])  
    Sn_Arithmetic[z,0]=100*(1-Thresholdn)
#Calculate geometric branch number similarity
    Thresholdn_Geo=np.abs((BRn_Geometric[4,0]-BRn_Geometric[z,0])/BRn_Geometric[4,0])  
    Sn_Geometric[z,0]=100*(1-Thresholdn_Geo)
# Part 2 (Branch length arithmetic and geometric similarirty)
#Calculate arithmetic and geometric branch length bifurcation ratio
#initial values
Tem_Sl=np.zeros((1,2))
BRl_Arithmetic=np.zeros((9,1))
BRl_Geometric=np.zeros((9,1))
Sl_Arithmetic=np.zeros((9,1))
Sl_Geometric=np.zeros((9,1))
for j in range(9):
    for i in range(2):
        R1=TreeShapedDataset.iloc[i+3,j]      
        R2=TreeShapedDataset.iloc[i+4,j]
        Tem_Sl[0,i]=R2/R1
#arithmetic branch length bifurcation ratio
    BRl_Arithmetic[j,0]=np.average(Tem_Sl)
#geometric branch length bifurcation ratio
    BRl_Geometric[j,0]=np.exp(np.mean(np.log(Tem_Sl)))  
for z in range (9):
#Calculate arithmetic branch length similarity
    Thresholdl=np.abs((BRl_Arithmetic[4,0]-BRl_Arithmetic[z,0])/BRl_Arithmetic[4,0])  
    Sl_Arithmetic[z,0]=100*(1-Thresholdl)
#Calculate geometric branch length similarity
    Thresholdl_Geo=np.abs((BRl_Geometric[4,0]-BRl_Geometric[z,0])/BRl_Geometric[4,0]) #BRn[4,0] is the reference tree-shaped network
    Sl_Geometric[z,0]=100*(1-Thresholdl_Geo)   
# Part 3 (Branch area arithmetic and geometric similarirty)
#Calculate arithmetic and geometric branch area bifurcation ratio
#initial values
Tem_Sa=np.zeros((1,2))
BRa_Arithmetic=np.zeros((9,1))
BRa_Geometric=np.zeros((9,1))
Sa_Arithmetic=np.zeros((9,1))
Sa_Geometric=np.zeros((9,1))
for j in range(9):
    for i in range(2):
        R1=TreeShapedDataset.iloc[i+6,j]
        R2=TreeShapedDataset.iloc[i+7,j]
        Tem_Sa[0,i]=R1/R2
#arithmetic branch area bifurcation ratio
    BRa_Arithmetic[j,0]=np.average(Tem_Sa)  #arithmetic mean bifurcation ratio
#geometric branch area bifurcation ratio
    BRa_Geometric[j,0]=np.exp(np.mean(np.log(Tem_Sa)))  #geometric mean computation
for z in range (9):
#Calculate arithmetic branch area similarity
    Thresholda=np.abs((BRa_Arithmetic[4,0]-BRa_Arithmetic[z,0])/BRa_Arithmetic[4,0])  
    Sa_Arithmetic[z,0]=100*(1-Thresholda)
#Calculate geometric branch area similarity
    Thresholda_Geo=np.abs((BRa_Geometric[4,0]-BRa_Geometric[z,0])/BRa_Geometric[4,0])
    Sa_Geometric[z,0]=100*(1-Thresholda_Geo)

#Calculate overall inner arithmetic and geometric similarity
OverallArithmeticsimilarity=np.zeros((9,1))
OverallGeometricsimilarity=np.zeros((9,1))
for x in range (9):
# Overall inner arithmetic similarity
    OverallArithmeticsimilarity[x,0]=((Sn_Arithmetic[x,0])+(Sl_Arithmetic[x,0])+(Sa_Arithmetic[x,0]))/3
# Overall inner geometric similarity
    OverallGeometricsimilarity[x,0]=((Sn_Geometric[x,0])*(Sl_Geometric[x,0])*(Sa_Geometric[x,0]))**(1/3)
#Arithmetic BR and inner arithmetic similarities in table form
BR_Arithmetic=np.hstack((BRn_Arithmetic,BRl_Arithmetic,BRa_Arithmetic))
Inner_overallArithSimilarity=np.hstack((Sn_Arithmetic,Sl_Arithmetic,Sa_Arithmetic,OverallArithmeticsimilarity))
print('Arithmetic Bifurcation Ratio\n','    BRn          BRl       BRa           \n',BR_Arithmetic)
print()
print('Inner_overallArithSimilarity\n','      Sn             Sl           Sa           S\n',Inner_overallArithSimilarity)
#Geometric BR and inner arithmetic similarities in table form
BR_Geometric=np.hstack((BRn_Geometric,BRl_Geometric,BRa_Geometric))
Inner_overallGeometricSimilarity=np.hstack((Sn_Geometric,Sl_Geometric,Sa_Geometric,OverallGeometricsimilarity))
print('----------------------------------------------------------------------------')
print('Geometric Bifurcation Ratio\n','    BRn          BRl       BRa           \n',BR_Geometric)
print()
print('Inner_overallGeometricSimilarity\n','      Sn             Sl           Sa           S\n',Inner_overallGeometricSimilarity)

Arithmetic Bifurcation Ratio
     BRn          BRl       BRa           
 [[3.33333333 1.37805202 1.82814827]
 [3.875      1.68875645 1.90388813]
 [3.625      1.6961204  1.61835232]
 [4.         1.70640816 1.66944113]
 [3.875      1.79480519 1.93187602]
 [4.25       2.2150138  1.80321499]
 [7.08333333 2.60911977 1.8468685 ]
 [3.33333333 1.34748107 1.54428749]
 [6.5        1.83918919 1.8029168 ]]

Inner_overallArithSimilarity
       Sn             Sl           Sa           S
 [[ 86.02150538  76.78003275  94.63072425  85.81075413]
 [100.          94.09135082  98.55125858  97.54753647]
 [ 93.5483871   94.5016432   83.77102363  90.60701798]
 [ 96.77419355  95.07483978  86.41554168  92.75485834]
 [100.         100.         100.         100.        ]
 [ 90.32258065  76.58750873  93.34009898  86.75006279]
 [ 17.20430108  54.62936163  95.59974241  55.81113504]
 [ 86.02150538  75.07673136  79.93719446  80.34514373]
 [ 32.25806452  97.5270857   93.32466374  74.36993798]]
-------------------------